accounts/urls.py
from django.urls import path
from . import views 
app_name = 'accounts'
urlpatterns  = [

    path('login/', views.UserloginView.as_view(), name='login'), 
    path('logout/', views.UserLogoutView.as_view(),name='logout'), 
    path('create-account/', views.CreateNewUserView.as_view(),name='create_account'), 
    path('change-password/', views.PasswordChangeView.as_view(),name='password_change'), 
    path('reset-password/', views.PasswordResetView.as_view(), name='password-reset'),
    path('reset-password-email/', views.PasswordResetEmailView.as_view(), name='password_reset_email'),
    path('reset-password/<int:uid>/', views.ResetPasswordView.as_view(), name='reset_password'),
    path('profile/', views.ProfileView.as_view(), name='profile'),



]

dash/urls.py
from django.urls import path
from . import  views 


app_name = 'dash'

urlpatterns = [
    
    path('', views.IndexView.as_view(), name='index'), 

]

jansava/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')), 
    path('services/',include('services.urls',namespace='service')),
    
    path('', include('dash.urls', namespace='dash')), 
    
    

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
from django.forms.formsets import formset_factory



class Profile(models.Model):

    class UserRole(models.TextChoices):

        CI = 'CI', 'Citizens'
        OF = 'OF', 'Officer'
        MA = 'MA','Manager'
        A ='A','Admin'


    class GenderChoice(models.TextChoices):
        M = 'M',"Male"
        F = 'F', "Female"
        
    
    
    id = models.PositiveIntegerField(primary_key=True, verbose_name='your adhar number ', unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    name = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField()
    gender = models.CharField(max_length=2, choices=GenderChoice)
    phone = models.CharField(max_length=12)
    user_role = models.CharField(max_length=2, choices=UserRole, default=UserRole.CI)
    picture = models.ImageField(upload_to='resident/images',null=True,blank=True)
    zip_code  = models.CharField(max_length=12)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at= models.DateTimeField(auto_now=True)



    def __str__(self):
        return f'profile {self.name}'
    



 

    

accounts/forms.py
from django import forms
from django.contrib.auth.models import User 
from .models import (
    Profile,


)

# user login form 



class UserLoginForm(forms.Form):

    username = forms.CharField(max_length=60 ,help_text="Enter your username Or email  ")
    password  = forms.CharField(max_length=20, widget=forms.PasswordInput())



    
class CreateUserForm(forms.ModelForm):

    password = forms.CharField(
        max_length=20, 
        widget=forms.PasswordInput(attrs={'placeholder': "Enter password"})
    )
    password2 = forms.CharField(
        max_length=20, 
        widget=forms.PasswordInput(attrs={'placeholder': "Confirm password"})
    )

    class Meta:
        model = User  
        fields = ['username', 'email']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")

        if password and password2 and password != password2:
            self.add_error('password2', "Passwords do not match.")
        return cleaned_data



class PasswordChangeForm(forms.Form):

    username  = forms.CharField(max_length=50,  help_text="Your username or email ")
    password = forms.CharField(widget=forms.PasswordInput(), help_text="Current password ")
    new_password = forms.CharField(widget=forms.PasswordInput(), help_text="New  password ")


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("new_password")
     

        if password and len(password)<12:
            self.add_error('new_password', "Your password is less secure make sure you create a strong password more than 12 character ")
        return cleaned_data


from django import forms

class PasswordResetForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'New Password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            self.add_error('confirm_password', "Passwords do not match.")



class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import login, logout , authenticate
from django.views import generic
from django.views import View
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives, send_mail
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django import forms 
from .signals import (
    password_reset, 
    password_changed
)

from django.forms import formset_factory, inlineformset_factory, modelformset_factory


from .models import (
    Profile,

)


from .forms import (
    UserLoginForm, CreateUserForm, PasswordChangeForm, PasswordResetForm, 
    ProfileForm
)

class  UserloginView(View):
    redirect_field_name = 'next'


    form = UserLoginForm()
    def get(self, request, *args, **kwargs):
        next_url = request.GET.get(self.redirect_field_name, "")
        
        context = {
            'form': self.form, 
             "next": next_url,  
        }
        return render(request, 'accounts/login.html', context )
    
    def post(self, request, *args, **kwargs):

        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd['username']
            password = cd['password']
            next_url = (
            request.POST.get(self.redirect_field_name)
            or request.GET.get(self.redirect_field_name)
            )
            

            user = authenticate(request,username=username, password=password)
            if user is not None:
                login(request, user)
                if next_url:
                    return redirect(next_url)
                return redirect('dash:index')
                
        else:
            messages.error(request, "Please enter the correct credentials ")

        return render(request, 'accounts/login.html', {"form": form})
        


class UserLogoutView(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs ):

        return render(request, 'accounts/logout_confirm.html')
    

    def post(self, request, *args, **kwargs):

        logout(request)
        return redirect('dash:index')
    



class CreateNewUserView(View):

    def get(self,request, *args, **kwargs):

        form = CreateUserForm()
        context = {
            'form': form,

        }
        return render(request, 'accounts/create_account.html', context )
    
    def post(self, request, *args, **kwargs):

        form = CreateUserForm(request.POST)
        if form.is_valid():

            cd  = form.cleaned_data
            password = cd['password']
            username = cd['username']
            email = cd['email']

            try:
                user  = User.objects.create_user(username=username, email=email, password=password)
            except Exception as e :
                print(e)
                print('the fucking problem in  the create user ')
            login(request, user)
            return redirect('accounts:profile')
        
        else: 
            messages.error(request, "Please enter the right credentails ")
            
        return render(request, 'accounts/create_account.html', {"form": form})
    
class PasswordChangeView(View):
    
    def get(self, request, *args, **kwargs):
        form = PasswordChangeForm()

        return render(request, 'accounts/password_change.html', {"form": form})
    
    def post(self, request, *args, **kwargs):

        form = PasswordChangeForm(request.POST)

        if form.is_valid():

            cd = form.cleaned_data
            username = cd['username']
            password = cd['password']
            new_password = cd['new_password']

            user = authenticate(request,username=username, password=password)
            if user is not None:
                
                user.set_password(new_password)
                user.save()
                password_changed.send(sender=user)
                login(request,user)
                messages.success(request, 'Password change successfuly ')
                return redirect('dash:index')
            else:
                # if the user is none 
                messages.error(request, "Please enter the right credentials ")
        
        return render(request, 'accounts/password_change.html', {"form": form})
    
            



class PasswordResetView(generic.TemplateView):
    template_name = 'accounts/reset.html'
    

class PasswordResetEmailView(View):

    def post(self, request):
        email = request.POST.get("email")
        user = User.objects.filter(email=email).first()

        if user:
            reset_link = request.build_absolute_uri(
                reverse('accounts:reset_password', kwargs={'uid': user.id})
            )

            subject = "Reset Your Password"
            from_email = "admin@yourdomain.com"
            to_email = [user.email]

            context = {
                'username': user.username,
                'reset_link': reset_link
            }

            html_content = render_to_string('accounts/password_reset_email.html', context)
            text_content = f"Hi {user.username}, click the link to reset your password: {reset_link}"

            email_message = EmailMultiAlternatives(subject, text_content, from_email, to_email)
            email_message.attach_alternative(html_content, "text/html")
            email_message.send()

        return render(request, 'accounts/email_confirmation.html')
    


class ResetPasswordView(View):

    def get(self, request, uid):
        form = PasswordResetForm()
        return render(request, 'accounts/reset_password_form.html', {'form': form})

    def post(self, request, uid):
        user = get_object_or_404(User, pk=uid)
        form = PasswordResetForm(request.POST)

        if form.is_valid():
            password = form.cleaned_data.get('password')
            user.set_password(password)
            user.save()
            password_reset.send(sender=user)
            messages.success(request, 'Password reset successful.')
            return redirect('accounts:login')

        messages.error(request, 'Please correct the errors below.')
        return render(request, 'accounts/reset_password_form.html', {'form': form})



class ProfileView(LoginRequiredMixin,View):


    def get(self, request, *args, **kwargs):
        
        user = request.user 
        if hasattr(user,'profile'):
            context = {
                'profile': user.profile
            }
            return render(request,'profile/profile.html', context  )
        
        
        context = {
            'form': ProfileForm(), 
            
            
        }
        return render(request, 'profile/create_profile.html', context )
    
    def post(self, request, *args, **kwargs):

        form = ProfileForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            profile = form.save(commit=False)
            profile.user = request.user 
            profile.save()

            # returning the user somewhere like index 
            return redirect('dash:index')
        
        context = {
            'form': form 
        }
        return render(request, 'profile/create_profile.html', context )


    

accounts/templates/accounts/account_created_email.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hey {{username}}, You man you did man </h1>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Non id dolor sit ab blanditiis at placeat voluptatem maiores facilis molestias! Aliquam quidem praesentium accusantium ut doloribus adipisci unde atque quisquam?</p>
    
</body>
</html>

accounts/templates/accounts/create_account.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hey welcome to the community! Enter the correct credentials </h1>
    <form action="" method="post">

        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create Account">
        
    </form>
</body>
</html>

accounts/templates/accounts/email_confirmation.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Confirmation</title>
</head>
<body>
    

    <h1>We have sended you an email please check it and reset your password </h1>

    
</body>
</html>

accounts/templates/accounts/email_send.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>The email is send to your email please check and reset your password </h1>
    {{link}}

</body>
</html>

accounts/templates/accounts/login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Please enter the correct credentials </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}

         {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        
        <input type="submit" value="login">
        
    </form>
</body>
</html>

accounts/templates/accounts/logout_confirm.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout Confirm Page </title>
</head>
<body>
    <h1>hey {{username}} are you sure  you want to logout from our community? </h1>
    <p>By doing this your data, setting will also delete </p>

    <form action="" method="post">

        {% csrf_token %}
        <input type="submit" value="Confirm Logut">
        

    </form>
</body>
</html>

accounts/templates/accounts/password_change.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Please Enter the correct credentials </h1>

    <form action="" method="post">

        {% csrf_token %}
        {% for field in form %}

            {{field.label_tag}} <br>
            {{field}} <br>
            {{field.errors}}
            <br>
        {% endfor %}
        <input type="submit" value="change password">
        
    </form>
    
</body>
</html>

accounts/templates/accounts/password_change_reset.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hey</title>
</head>
<body>
    <h1>hey {{username}}, you have done something </h1>

    {% if p_change %}
        <h2>hey you have changes your password successufly man what a please way to do this</h2>

    {% else %} 
        <h2>hey you reset your password  successufly man what a please way to do this</h2>


    {% endif %}
</body>
</html>

accounts/templates/accounts/password_reset_email.html
<h2>Hi {{ username }}</h2>
<p>You requested to reset your password.</p>
<p>Click the link below to set a new password:</p>
<a href="{{ reset_link }}">{{ reset_link }}</a>

accounts/templates/accounts/reset.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset </title>
</head>
<body>
    
    <h1>Plesae Enter your registered email addresss </h1>

    <form action="{% url 'accounts:password_reset_email' %}" method="post">

        {% csrf_token %}
        <input type="email" name="email" placeholder="registered email "><br>
        <input type="submit" value="send  email ">

    </form>


</body>
</html>

accounts/templates/accounts/reset_password_form.html
<form action="" method="post">

    {% csrf_token %}

    {% for field in form %}

        {{field.label_tag}} <br>
        {{field}} <br>
        {{field.errors}}
        <br>
        

    {% endfor %}
    <input type="submit" value="change password">


</form>